services:

  mongo:
    image: mongo:6.0.5
    restart: always
    ports:
      - '27017:27017'
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 20s
      timeout: 10s
      retries: 2

  node-graphql:
    build: .
    volumes: 
      - .:/opt/node-graphql/
    # image: node-graphql
    restart: always
    ports:
      - 3000:3000
    depends_on:
      mongo:
        condition: "service_healthy"
    healthcheck:
      test: curl http://localhost:3000/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 2